'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { HudPanel } from './HudPanel'; import { LoadingScreen } from './LoadingScreen'; import { EncounterPanel } from './EncounterPanel'; import { PlayerState } from '@/game/types/player'; import { EncounterTemplate } from '@/game/types/encounter';
const anonKey='soa-anon-id';
export function GameShell(){ const [loading,setLoading]=useState(true); const [player,setPlayer]=useState<PlayerState|null>(null); const [seed,setSeed]=useState(''); const [worldId,setWorldId]=useState(''); const [enc,setEnc]=useState<EncounterTemplate|null>(null); const [aiText,setAiText]=useState<string|null>(null); const wrap=useRef<HTMLDivElement>(null);
const anonId=useMemo(()=>{if(typeof window==='undefined')return ''; let id=localStorage.getItem(anonKey); if(!id){id=crypto.randomUUID();localStorage.setItem(anonKey,id);} return id;},[]);
useEffect(()=>{(async()=>{ const load=await fetch('/api/world/load',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:anonId})}).then(r=>r.json()); const payload=load.found?load:await fetch('/api/world/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:anonId})}).then(r=>r.json()).then(()=>fetch('/api/world/load',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:anonId})}).then(r=>r.json())); setPlayer(payload.player); setSeed(payload.seed); setWorldId(payload.player.worldId); setLoading(false); })();},[anonId]);
useEffect(()=>{if(loading||!wrap.current)return; let game:any; import('@/game/phaser/Game').then(({createGame})=>{ game=createGame('phaser-root', async (q:number,r:number)=>{ if(!player) return; const res=await fetch('/api/world/explore-hex',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({worldId,playerId:player.playerId,q,r,seed})}).then(r=>r.json()); if(res.encounter) setEnc(res.encounter); setPlayer({...player,currentQ:q,currentR:r}); });}); return ()=>game?.destroy(true);},[loading,player,seed,worldId]);
if(loading||!player) return <LoadingScreen/>;
return <main style={{display:'grid',gridTemplateColumns:'1fr 280px',gap:16,padding:16}}><section className='panel' style={{padding:8}}><div id='phaser-root' ref={wrap}/></section><div style={{display:'flex',flexDirection:'column',gap:12}}><HudPanel player={player}/><EncounterPanel encounter={enc} aiText={aiText} onChoose={async()=>{ if(!enc||!player) return; const outcome:any={}; if(enc.type==='treasure'){ outcome.gold=10; setPlayer({...player,gold:player.gold+10}); } if(enc.type==='hazard'){ outcome.hpLoss=3; setPlayer({...player,hp:Math.max(1,player.hp-3)});} if(enc.type==='shrine'){outcome.shards=1;outcome.discoveredFact='An old wind-clan rune mentions the Skyglass Oath.'; setPlayer({...player,shards:player.shards+1});}
const event={type:enc.type,terrain:'unknown',eventTitle:enc.title,description:enc.description,choiceMade:enc.choice,outcome}; const done=await fetch('/api/world/explore-hex',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({worldId,playerId:player.playerId,q:player.currentQ,r:player.currentR,resolveEncounter:event,choiceMade:enc.choice})}).then(r=>r.json()); setAiText(done.aiText??null); setEnc(null);
}}/></div></main>; }
